
CREATE TABLE IF NOT EXISTS Auteur(
    Id_auteur INT PRIMARY KEY AUTO_INCREMENT,
    privilege INT NOT NULL,
    Nom VARCHAR(255) NOT NULL,
    Prenom VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Mot de passe VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS Article(
    Id_article INT PRIMARY KEY AUTO_INCREMENT,
    Titre VARCHAR(255) NOT NULL,
    Contenu TEXT NOT NULL,
    Date DATETIME NOT NULL,
    id_auteur INT NOT NULL,
    FOREIGN KEY (id_auteur) REFERENCES Auteur (Id_auteur)
);
