
CREATE TABLE IF NOT EXISTS Auteur(
    Id_auteur INT PRIMARY KEY AUTOINCREMENT,
    Nom VARCHAR(255) NOT NULL,
    Prenom VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Article(
    Id_article INT PRIMARY KEY AUTOINCREMENT,
    Titre VARCHAR(255) NOT NULL,
    Contenu TEXT NOT NULL,
    Date DATETIME NOT NULL,
    id_auteur INT NOT NULL
    FOREIGN KEY (id_auteur) REFERENCES Auteur (Id_auteur)
);